export const currencySymbol = "₹";
export const multiplier = 'x';
export const shippingCost = 40;
export const additionText = "Safe and Secure Payments. Easy returns. 100% Authentic products.";
export const cartEmptyText = "Your cart is empty!";
export const additionCartEmptyText = "Looks like you haven't added any items to the cart yet.";
export const address1 = "Near KFC, 1st Cross, 1st Main, Koramangala 1st Block, Bangalore";
export const address2 = "Atri Hall of Residence, near VSSUT college,  Burla, Sambalpur, Odisha";
export const address3 = "Infront of Telephone Exchange Office,Jajpur Road, 768017 , Odisha";