import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { Header } from "@layout/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Checkout Page",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/" sizes="any" type="image/png" />
      </head>
      <body className={inter.className}>
      <Toaster position="top-right" />
          <Header />
          {children}
      </body>
    </html>
  );
}
