import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@layout/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Checkout Page",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="icon"
          href="/"
          sizes="any"
          type="image/png"
        />
      </head>
      <body className={inter.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
